# Change the following to your desired values:
#   __ACCOUNT_NUMBER__
#   __ECR_REGION__
#   __ECR_REPOSITORY_NAME__
#   __ECS_CONTAINER_NAME__

version: 0.2
phases:
  install:
    runtime-versions:
      docker: 20
      java: corretto17
    commands:
      - yum update -y
      - echo "Installing Maven..."
      - wget https://downloads.apache.org/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz
      - tar xzvf apache-maven-3.6.3-bin.tar.gz
      - export PATH=$PATH:`pwd`/apache-maven-3.6.3/bin
      - mvn -version
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-west-2 --no-include-email)
      - REPOSITORY_URI=418683829126.dkr.ecr.us-west-2.amazonaws.com/ecommerce-product-service
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Running Maven build...
      - mvn clean install
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
#      - printf '[{"name”:"__ECS_CONTAINER_NAME__","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json